# Generated by Django 5.1.1 on 2024-09-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_gamesession_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="conversation_goal",
            field=models.CharField(
                default="Complete a data analysis task", max_length=200
            ),
        ),
    ]
