# Generated by Django 5.1.1 on 2024-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_gamesession_conversation_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="rating_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="total_rating",
            field=models.FloatField(default=0),
        ),
    ]
